// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtZspQr1xBZcAP9_rtZWSKv9sNT7kxPC8',
    appId: '1:902383379237:web:3e0c3187de0464dfdcb0cc',
    messagingSenderId: '902383379237',
    projectId: 'flutter-quiz-594ec',
    authDomain: 'flutter-quiz-594ec.firebaseapp.com',
    storageBucket: 'flutter-quiz-594ec.firebasestorage.app',
    measurementId: 'G-TN9EEBSETL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7uU05nKxBA5HWfkuWkQSKwyrWyCtWgdw',
    appId: '1:902383379237:android:c45ece816c60acc2dcb0cc',
    messagingSenderId: '902383379237',
    projectId: 'flutter-quiz-594ec',
    storageBucket: 'flutter-quiz-594ec.firebasestorage.app',
  );
}
